name: Setup
description: Setup Go
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # actions/setup-go@v3
      name: Set up Go
      with:
        go-version: 1.25
        cache: true
