name: Setup
description: Setup Go
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # actions/setup-go@v3
      name: Set up Go
      with:
        go-version: 1.26
        cache: true
