name: Setup
description: Setup Go
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@a5f9b05d2d216f63e13859e0d847461041025775 # actions/setup-go@v3
      name: Set up Go
      with:
        go-version: 1.19
        cache: true
