version: "2"

linters:
  enable:
  - depguard
  - errname
  - errorlint
  - errcheck
  - unused
  - godot
  - gosec
  - misspell
  - revive
  - thelper
  - unconvert
  - whitespace
  - staticcheck
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: 'github.com/pkg/errors'
              desc: 'the github.com/pkg/errors is deprecated, use stdlib instead'
