version: 2

linters:
  enable:
  - depguard
  - errname
  - errorlint
  - errcheck
  - unused
  - godot
  - goerr113
  - gofmt
  - gofumpt
  - gosec
  - misspell
  - revive
  - thelper
  - unconvert
  - whitespace
  - staticcheck
  disable:
  - structcheck

linters-settings:
  depguard:
    rules:
      main:
        deny:
          - pkg: 'github.com/pkg/errors'
            desc: 'the github.com/pkg/errors is deprecated, use stdlib instead'
